language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- travis_retry pip install -r requirements.txt -r requirements-test.txt -e .
- travis_retry pip install coverage coveralls
services:
- redis-server
before_script:
- psql -c 'create database test;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d test
- psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d test
script: py.test --pep8 --flakes -v
after_script:
- coveralls
branches:
  only:
  - master
