language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
services:
- redis-server
- rabbitmq
before_script:
- psql -c 'create database test;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
- psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
script: coverage run --source=gfsad setup.py test
after_success: coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_ed430a932405_key -iv $encrypted_ed430a932405_iv
  -in google_api_key.enc -out google_api.key -d
