language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
services:
  - redis-server
  - rabbitmq
script: coverage run --source=gfsad setup.py test
after_success: coveralls
env:
  global:
